apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: backend-image
    newName: 000000000000.dkr.ecr.us-east-1.host.docker.internal:4566/ashwin11-microservice-app-backend-ecr
    newTag: latest
