apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Skaffold will automatically inject the `images:` block below here.
images:
  - name: backend-image
    newName: awsls ecr create-repository --repository-name ashwin11-microservice-app-backend-ecr
    newTag: latest
