apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: backend-image
    newName: docker.io/11aashwin/ashwin11-microservice-app-backend-ecr
    newTag: fea4b8a8

secretGenerator:
  - name: backend-db-secret
    literals:
      - DATABASE_URL=postgresql://dbadmin:dbpassword123@host.docker.internal:4510/backenddb

generatorOptions:
  disableNameSuffixHash: true
