apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: agrocd-microservices

build:
  artifacts:
    # 1. Frontend Build Config
    - image: docker.io/11aashwin/ashwin11-microservice-app-frontend-ec
      context: services/frontend
      docker:
        dockerfile: Dockerfile

    #2. Backend build config
    - image: docker.io/11aashwin/ashwin11-microservice-app-backend-ecr
      context: services/backend
      docker:
        dockerfile: Dockerfile

# 3. Kustomize Patching
manifests:
  kustomize:
    paths:
      # Skaffold now patches both pipelines independently
      - k8s-kustomize/frontend/overlays/development
      - k8s-kustomize/backend/overlays/development
