apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: frontend-image
    newName: localhost:4566/ashwin11-microservice-app-frontend-ecr
    newTag: d60eed1d
