apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: frontend-image
    newName: docker.io/11aashwin/ashwin11-microservice-app-frontend-ec
    newTag: 1d855ab8
