# Same as BLUE , because when using GREEN , it will overlay with the changes mentioned witht the base dir
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../../../base

patches:
- path: image-and-label-patch.yaml
- path: service-selector-patch.yaml
- path: ingress-host-patch.yaml
- path: env-patch.yaml