apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: currency-converter
spec:
  template:
    spec:
      containers:
      - name: currency-converter
        image: 538153606685.dkr.ecr.us-east-1.amazonaws.com/currencyconverter:v2