apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../../base
patches:
- path: image-patch.yaml
  target:
    kind: Rollout #this is changed here , we not target the Rollout, not deployment
    name: currency-converter