apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currencyconverter-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Aashwin11/AgroCdAppDeploy-FORKED.git'
    targetRevision: applicationsetup-Aniket-BG
    path: k8s-kustomize/overlays/production/green

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

