apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/Aashwin11/AgroCdAppDeploy-FORKED.git"
    targetRevision: argocd-ai-BRANCH
    path: k8s-kustomize/backend/overlays/development
  destination:
    server: "https://kubernetes.default.svc"
    # INJECTS NAMESPACE INTO ALL BACKEND YAMLs
    namespace: microservice-app-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
