apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/Aashwin11/AgroCdAppDeploy-FORKED.git"
    targetRevision: argocd-ai-BRANCH
    path: k8s-kustomize/frontend/overlays/development
  destination:
    server: "https://kubernetes.default.svc"
    # INJECTS NAMESPACE INTO ALL FRONTEND YAMLs
    namespace: microservice-app-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
