apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  # Base64 encoded PostgreSQL connection string
  #Command:  echo -n "postgresql://postgres:postgres@localhost:5432/Fastapi_db_table" | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGxvY2FsaG9zdDo1NDMyL0Zhc3RhcGlfZGJfdGFibGU=
