apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Backend Resources
  - backend-secret.yaml
  - backend-services.yaml
  - backend-rollout.yaml
  - backend-hpa.yaml
  # Frontend Resources
  - frontend-services.yaml
  - frontend-rollout.yaml
  - frontend-ingress.yaml
